version: '3.7'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: yFodXR4mdFErATYsUrBvE4RPBiCUADbdONF6OMH28kA8gU0T6A
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: cQl0v1YZdXxAAhcnzedoOsxG5WoKx0qOJ8R9xpIvlDNiYpnhHe
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: cQl0v1YZdXxAAhcnzedoOsxG5WoKx0qOJ8R9xpIvlDNiYpnhHe
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
