version: '3.7'

services:
  concepts:
    image: concepts
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      ENDPOINT: http://prisma:4466
      SECRET: WZIpatNAZYbR7iGd6V6OhuBsxNkNAZoFBLt7ZaWU2D4mBJYqLY
      PRISMA_MANAGEMENT_API_JWT_SECRET: yFodXR4mdFErATYsUrBvE4RPBiCUADbdONF6OMH28kA8gU0T6A
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: cQl0v1YZdXxAAhcnzedoOsxG5WoKx0qOJ8R9xpIvlDNiYpnhHe
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: cQl0v1YZdXxAAhcnzedoOsxG5WoKx0qOJ8R9xpIvlDNiYpnhHe
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
